### ISSUE TITLE
Finish add-transaction function

### ISSUE THREAD

**Issue by roerohan** [roerohan/Sam-Bot#1]
https://github.com/roerohan/Sam-Bot/blob/5cec92f26a66b36b1d247516a198a6f9e079eb14/commands.js#L69-L82

> Follow coding style established in other functions
- Proper spacing (tabs not spacing)
- Comment lines if necessary
- Description in PR

> The PR must be made on the dev branch

**Comment by mlimos** [comment]
@roerohan I'd like to take this one, if nobody else has claimed it yet. Thanks!

**Comment by roerohan** [comment]
@mlimos go ahead!
