### ISSUE TITLE
Convert to switch case

### ISSUE THREAD

**Issue by roerohan** [roerohan/Sam-Bot#3]
Convert the code written in [index.js](https://github.com/roerohan/Sam-Bot/blob/master/index.js) to switch case.

Make a Pull Request on the dev branch.

**Comment by GabrielSBarros** [comment]
I'd like to take this one

**Comment by objNameGit** [comment]
i`m too try do it

**Comment by objNameGit** [comment]
> Convert the code written in [index.js](https://github.com/roerohan/Sam-Bot/blob/master/index.js) to switch case.
> 
> Make a Pull Request on the dev branch.

  user.username = message.from.username;
username convert to userName?
