### ISSUE TITLE
'message' is not defined, Switch case

### ISSUE THREAD

**Issue by roerohan** [roerohan/Sam-Bot#8]
https://github.com/roerohan/Sam-Bot/blob/027c93d121dbd4afb0503e0422bb5f35f2d78890/index.js#L185-L195

The default in switch case throws an error: 
```
ReferenceError: message is not defined
```

Push fix on branch dev.

**Comment by n8eloy** [comment]
Hey, I would like to work on this issue. Could you assign this to me?

**Comment by roerohan** [comment]
It got fixed.
